sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t stephy/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true stephy/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "ebs-demo"
  env: "Ebs-demo-env"
  bucket_name: "elasticbeanstalk-eu-north-1-384820790671"
  bucket_path: "ebs-demo"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY