sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t stephy/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true stephy/docker-react npm run test
